--lien couleurs http://doc.instantreality.org/tools/color_calculator/

local core = {}
local key = {}
local buf = {}

-- Color multipler
local COLOR_MUL = love._version >= "11.0" and 1 or 255

function key.setting() 
-- Setup keys config
key[0], key[1], key[2], key[3] = {}, {}, {}, {}
key[0].x = 551
key[0].y = -50 
key[0].width = 50 
key[0].height = 50 
key[0].mode = 0 
key[1].x = 631
key[1].y = -50 
key[1].width = 50 
key[1].height = 50 
key[1].mode = 0 
key[2].x = 711
key[2].y = -50 
key[2].width = 50 
key[2].height = 50 
key[2].mode = 0 
key[3].x = 792
key[3].y = -50 
key[3].width = 50 
key[3].height = 50 
key[3].mode = 0
end

function key.appendBuffer()
	if (math.random(1500) < 25) then
		-- Append number of items.
		core.touch = core.touch + 1
		--Create object depending on key config.
		buf [core.touch]={}
		buf [core.touch].x = key[math.random(4) - 1].x
		buf [core.touch].y = -50
	end
end
	if (math.random(1500) < 25 ) then
		buf[core.touch].anim = 1
	end

function key.scrolling()
	for i =0,core.touch do
		-- Scrolling objects
		if (buf[i] ~= nil) then
			buf[i].y = buf[i].y + 3
		end
		-- Reset objects
		if (buf[i] ~= nil and buf[i].y == 600) then
			buf[i].y = nil
			buf[i].x = nil
			buf[i] = nil
		end
	end
end

function memoryCleaner() 
	-- Clean memory 
	core.mem = core.mem + 1 
	if (core.mem == 500) then 
		collectgarbage() 
	end 
end

function love.draw()
	core.ui()	
	for i = 0, core.touch do
		-- If object exists, print it with his right color
		if (buf[i] ~=nil) then
			love.graphics.setColor(1, 0.533, 0 ,1)
			love.graphics.rectangle("fill" , buf[i].x , buf[i].y, 50, 30)
		end
	end
	love.graphics.print("SCORE", 986, 318, 0, 4, 4)
	love.graphics.print(core.score, 986, 368, 0, 4, 4)
	love.graphics.setColor(1, 0.533, 0,1)
	if core.scene == 1 then
		core.drawSceneGame()
	end
	if core.scene == 0 then
		core.drawSceneMenu()
	end
end

function core.ui()
	love.graphics.setColor(255, 255, 255, 0.5) -- couleurs corde de la guitare
	love.graphics.rectangle("fill", 551, 0, 60, 800)
	love.graphics.rectangle("fill", 631, 0, 60, 800)
	love.graphics.rectangle("fill", 711, 0, 60, 800)
	love.graphics.rectangle("fill", 792, 0, 60, 800)
end

function love.load()
	success=love.window.setMode(1366,768,flags)
	-- love.graphics.setBackgroundColor(0.443, 0.254, 0.117, 1)  -- Couleur de fond
	core["scene"] = 0 -- Scene : menu /game /other
	--core[""]
	core["touch"] = -1 -- Nbr of items generated by the game
	core["mem"]= 0 -- Garbage collector cycles
	key.setting()
	core["score"] = 0
	core["combo"] = 0
	core["startTime"] = 0
	core["logo2"] = love.graphics.newImage("/img/5.png")
	core["endTime"] = 215
	love.keyboard.setKeyRepeat(false)
	core["q"] = 0
	core["s"] = 0
	core["d"] = 0
	core["f"] = 0
end
	core["logo"] = love.graphics.newImage("/img/2.jpg") -- affichage image

function key.checkClicked(x)
	for i = 0, core.touch do
		if (buf[i] ~= nil and buf[i].x == x and buf[i].y > 500 and buf[i].y < 550) then
			buf[i].y = nil
			buf[i].x = nil
			buf[i] = nil
			return (1)
		end
	end
	return(0)
end

function key.fadeOut()
	for i = 0, core.touch do 
		if (buf[i] ~= nil and buf[i].anim < 1) then 
			buf[i].anim = buf[i].anim - 0.1 
		end 
		if (buf[i] ~= nil and buf[i].anim == 0) then 
			buf[i].y = nil 
			buf[i].x = nil 
			buf[i] = nil 
		end 
	end 
end

function love.update(dt)
	dt = math.min(dt, 1/60)
	if core.scene == 1 then
		if love.timer.getTime() - core.startTime >= core.endTime then
		buf = {}
		love.audio.stop()
		core.scene = 0
		end
		key.appendBuffer()
		key.scrolling()
		memoryCleaner()
		-- core["music"] = love.audio.newSource("/sound/AlanWalkerGuitar.mp3", 'stream')
		-- love.audio.play(core.music)
	end
	if core.scene == 0 then
		if love.mouse.isDown(1) then
			core.startTime = love.timer.getTime()
			core.scene = 1
		end
	end
end

function core.drawSceneGame()
	love.graphics.draw(core.logo2, 0, 0)
	love.graphics.print("Current FPS: "..tostring(love.timer.getFPS( )), 100, 100)
	core.ui()
	for i = 0, core.touch do
		-- If object exists, print it wish his right color.
		if (buf[i] ~= nil) then
			love.graphics.setColor(255, 0,0, 1)
			love.graphics.rectangle("fill", buf[i].x, buf[i].y, 50, 30)
			if buf[i].y == 580 and core.score>0 then
				core.score = core.score - 10
			end
		end
	end
	love.graphics.setColor(255, 255, 255 ,1)	-- couleur corde horizontal
	love.graphics.rectangle("fill", 551, 512, 301, 38) -- corde horizontal
	
	-- Score Part
	love.graphics.print("SCORE:", 986, 318, 0, 6, 6)
	love.graphics.print(core.score, 986,368, 0, 6, 6)
	love.graphics.setColor(255, 0, 0, 1)
	
	-- Combo part
	love.graphics.print("Combo x "..tostring(core.combo,986,310))
	love.graphics.print(core.combo,300,310,0,8,8)

	if core.q == 1 then
		love.graphics.setColor(1, 0, 0, 1)
		love.graphics.rectangle("fill", 551, 510, 60, 40)
	end
	if core.s == 1 then
		love.graphics.setColor(1, 1, 0, 1)
		love.graphics.rectangle("fill", 631, 510, 60, 40)
	end
	if core.d == 1 then
		love.graphics.setColor(0, 1, 0, 1)
		love.graphics.rectangle("fill", 711, 510, 60, 40)
	end
	if core.f == 1 then
		love.graphics.setColor(0, 0, 1, 1)
		love.graphics.rectangle("fill", 792, 510, 60, 40)
	end
end

function love.keypressed(myKey)
	if myKey == "q" then
		if key.checkClicked(551) == 1 then
			core.score = core.score + 100
			core.combo = core.combo + 1
		else
			core.combo = 0
		end
	end
	if myKey == "s" then
		if key.checkClicked(631) == 1 then
			core.score = core.score + 100
			core.combo = core.combo + 1
		else
			core.combo = 0
		end
	end
	if myKey == "d" then
		if key.checkClicked(711) == 1 then
			core.score = core.score + 100
			core.combo = core.combo + 1
		else
			core.combo = 0
		end
	end
	if myKey == "f" then
		if key.checkClicked(792) == 1 then
			core.score = core.score + 100
			core.combo = core.combo + 1
		else
			core.combo = 0
		end
	end

	if myKey == "q" then
		core.q = 1
	end
	if myKey == "s" then
		core.s = 1
	end
	if myKey == "d" then
		core.d = 1
	end
	if myKey == "f" then
		core.f = 1
	end
	animation()
end

function core.drawSceneMenu()
	love.graphics.draw(core.logo, 0, 0) --- image
	love.graphics.print("Play", 616, 668, 0, 4, 4)
end

--function love.load()
--  printx = 0
--   printy = 0
--end

--function love.mousepressed(x, y, button)
--   if button == "l" then
--      printx = 616
--      printy = 668
--   end
--end

function animation()
	core['animation'] = {}
	core['animation'].q, core['animation'].s , core['animation'].d,
	core['animation'].f = 0, 0.2, 1, 1
	-- love.graphics.setColor(0, 0.2, 1, 1)
end

function love.keyreleased(key)
   if key == "q" then
      core.q = 0
   end
   if key == "s" then
      core.s = 0
   end
   if key == "d" then
      core.d = 0
   end
   if key == "f" then
      core.f = 0
   end
end
